name: rd-sharma-extractor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - pandas>=1.5.0
  - matplotlib>=3.5.0
  - seaborn>=0.12.0
  - scipy>=1.11.0
  - pillow>=9.0.0
  - requests>=2.28.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - notebook>=6.0.0
  - pip:
      - groq>=1.0.0
      - langchain>=0.1.0
      - faiss-cpu>=1.7.0
      - PyMuPDF>=1.23.0
      - easyocr>=1.7.0
      - sentence-transformers>=2.2.0
      - spacy>=3.5.0
      - pydantic>=2.0.0
      - typer>=0.9.0
      - rich>=13.0.0
      - python-dotenv>=0.19.0
      - pytest>=7.4.0
      - pytest-cov>=4.0.0
      - black>=23.0.0
      - flake8>=6.0.0
      - mypy>=1.0.0
      - psutil>=5.9.0
      - plotly>=5.15.0
      - bokeh>=3.2.0
